fix broken cell
Code was broken before, this enables the cell to be run. Fixed some typos and added "None" to the  function "make_simple_step_size_update_policy()" for the argument "num_adaption_steps", which otherwise returned the error:

make_simple_step_size_update_policy() missing 1 required positional argument: 'num_adaptation_steps'.

As per documentation, None may not be the best choice.